name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout daf-core-sql repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Avoid shallow clone so nbgv can do its work.
          repository: data-automation-framework/daf-core-sql
          path: daf-core-sql
      - name: Checkout daf-core-ssis repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Avoid shallow clone so nbgv can do its work.
          repository: data-automation-framework/daf-core-ssis
          path: daf-core-ssis
      - name: Checkout daf-core-adf repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Avoid shallow clone so nbgv can do its work.
          repository: data-automation-framework/daf-core-adf
          path: daf-core-adf
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # SDK Version to use.
          source-url: https://nuget.pkg.github.com/data-automation-framework/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore nuget packages for Sql
        run: dotnet restore daf-core-sql/Daf.Core.Sql/Daf.Core.Sql.csproj
      - name: Restore nuget packages for Ssis
        run: dotnet restore daf-core-ssis/Daf.Core.Ssis/Daf.Core.Ssis.csproj
      - name: Restore nuget packages for Adf
        run: dotnet restore daf-core-adf/Daf.Core.Adf/Daf.Core.Adf.csproj
      - name: Download latest DocFX release
        uses: carlosperate/download-file-action@v1.1.1
        with:
          file-url: 'https://github.com/dotnet/docfx/releases/latest/download/docfx.zip'
      - name: Unzip DocFX
        run: unzip docfx.zip -d docfx-tool
      - name: Set permissions
        run: chmod 777 docfx-tool/docfx.exe
      - name: Run DocFX
        run: docfx-tool/docfx.exe main/DocFX/docfx.json
